services:

  # ________ UTILS
  lch.translate.translations_helper:
    class: LchTranslateBundle\Utils\TranslationsHelper
    arguments: ['@parameter_bag', '@doctrine.orm.default_entity_manager']

  lch.translate.lang_switch_helper:
    class: LchTranslateBundle\Utils\LangSwitchHelper
    arguments: ['@lch.translate.translations_helper', '@router', '@request_stack', '@doctrine.orm.default_entity_manager']
  # ________

  # ________ SUBSCRIBERS
  LchTranslateBundle\EventListener\TranslatableEventSubscriber:
    arguments: ['@lch.translate.translations_helper']
    tags:
      - { name: doctrine.event_subscriber }
  # ________

  # ________ FORMS
  LchTranslateBundle\Form\Type\TranslatedParentType:
    arguments: ['@lch.translate.translations_helper', '@request_stack', '@event_dispatcher']
    tags:
      - { name: form.type }
  # ________

  # ________ TWIG
  LchTranslateBundle\Twig\LchTranslateBundleExtension:
    arguments: ['@lch.translate.lang_switch_helper']
    tags:
      - { name: twig.runtime }
  # ________
